version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: VaccinesTips
    restart: always
    environment:
      POSTGRES_DB: VaccinesTips-v1
      POSTGRES_USER: Api-VaccinesTips-v1
      POSTGRES_PASSWORD: Api-VaccinesTips-v1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: camilasepulveda@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: cami2002*
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
